### ISSUE TITLE
About how to use the DFC2018 dataset

### ISSUE THREAD

**Issue by YinWeiling** [marcelampc/mtl_aerial_images#1]
Hi, thank you for release the code. Could you please give some more details on how to use the DFC2018 dataset? The instruction says "Our scripts expect the datasets to be placed in datasets." but there is no fold named 'datasets'.

**Comment by blesaux** [comment]
Hi Weiling,

You will get your folder by typing "mkdir datasets"...

Then please check this website to know how to download the data from DFC2018:
[http://www.grss-ieee.org/community/technical-committees/data-fusion/2018-ieee-grss-data-fusion-contest/](http://www.grss-ieee.org/community/technical-committees/data-fusion/2018-ieee-grss-data-fusion-contest/)

It will involve register on DASE server:
[http://dase.grss-ieee.org/](http://dase.grss-ieee.org/)

And following instructions here: [http://hyperspectral.ee.uh.edu/?page_id=1075](http://hyperspectral.ee.uh.edu/?page_id=1075)

Best,
Bertrand Le Saux
[https://blesaux.github.io](https://blesaux.github.io)

**Comment by marcelampc** [comment]
Thanks for the complete answer, Bertrand!

Yin, I also use to create a symbolic link to an external 'datasets' folder, where I keep all data, so it's more straightforward to use with different codes....

**Comment by Diyago** [comment]
Is it possible to upload data somewhere else? For example to the kaggle https://www.kaggle.com/datasets . http://dase.ticinumaerospace.com/ - seems to be dead

**Comment by blesaux** [comment]
Hi,

this the wrong link.

The right one is http://dase.grss-ieee.org/

Best,
Bertrand
