### ISSUE TITLE
About DFC dataset

### ISSUE THREAD

**Issue by Luffy03** [marcelampc/mtl_aerial_images#5]
Sorry, i can not download dfc2018 dataset successfully. Would you please share the download link? Thank you very much! My email is 15274891948@163.com

**Comment by blesaux** [comment]
Hi!

Thanks for your interest in our algorithm!
The DFC2018 data can now be found on IEEE dataport:
[https://ieee-dataport.org/open-access/2018-ieee-grss-data-fusion-challenge-%E2%80%93-fusion-multispectral-lidar-and-hyperspectral-data](https://ieee-dataport.org/open-access/2018-ieee-grss-data-fusion-challenge-%E2%80%93-fusion-multispectral-lidar-and-hyperspectral-data)

Let us know if everything is going fine!
Kind regards,
Bertrand
